server:
  port: 2001

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  main:
    allow-circular-references: true
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
    alibaba:
      seata:
        #事务群组，要和下方vgroup-mapping保持一致（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping中存在,并且要保证多个群组情况下后缀名要保持一致-tx_group
        tx-service-group: default_tx_group

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: root

seata:
  application-id: ${spring.application.name}
  #数据源代理模式使用AT模式(可以不用配置，seata默认使用AT模式)
  data-source-proxy-mode: AT
  # 使用哪个事务组
  #tx-service-group: ${spring.application.name}-tx_group
  #事务群组（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping中存在,并且要保证多个群组情况下后缀名要保持一致-tx_group
  service:
    vgroup-mapping:
      default_tx_group: default

  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
#      username: nacos
#      password: nacos
      #seata分组名称
      cluster: default
      group: SEATA_GROUP
      #nacos命名空间ID
      namespace: public
      #seata服务名
      application: seata-server

  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
#      username: nacos
#      password: nacos
      #seata分组名称
      group: SEATA_GROUP
      #nacos命名空间ID
      namespace: public
      data-id: seataServer.propertie

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.jojo.springcloud.feign.RemoteService: debug
    com.jojo: debug
  root: info
  file:
    name: logs/${spring.application.name}/${spring.application.name}.out.log
  pattern:
    file: ${spring.application.name} %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level %logger{36} - %msg%n"