server:
  port: 8004
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: cloud-nacos-payment-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=ture&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  rabbitmq:
    host: 192.168.28.148
    port: 5672
    username: guest
    password: guest

mybatis:
  mapper-locations: classpath:mapper/*.xml