server:
  port: 8003

spring:
  application:
    name: cloud-zookeeper-payment-server
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=ture&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.28.148
    port: 5672
    username: guest
    password: guest

mybatis:
  mapper-locations: classpath:mapper/*.xml