server:
  port: 8004

spring:
  application:
    name: cloud-consul-payment-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=ture&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.28.148
    port: 5672
    username: guest
    password: guest

#  LOG setting
logging:
  level:
    com.jojo: debug
  root: info
  file:
    name: logs/${spring.application.name}/${spring.application.name}.out.log
  pattern:
    file: ${spring.application.name} %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level %logger{36} - %msg%n"

mybatis:
  mapper-locations: classpath:mapper/*.xml