server:
  port: 9002

spring:
  application:
    name: cloud-order-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=ture&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.28.148
    port: 5672
    username: guest
    password: guest

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.jojo: debug
  root: info
  file:
    name: logs/${spring.application.name}/${spring.application.name}.out.log
  pattern:
    file: ${spring.application.name} %d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level %logger{36} - %msg%n"

#Eureka config
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 #每隔30秒向eureka发送信息告诉服务还活着
    instance-id: payment9002
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:7001/eureka