server:
  port: 9527

spring:
  application:
    name: cloud-gateway-server
  cloud:
    gateway:
      routes:   #yml配置路由
        - id: payment_routh #payment_route      #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001            #匹配后提供服务的路由地址
          predicates:                           #断言，路径相匹配的进行路由
            - Path=/payment/get/**

#        - id: payment_routh2 #payment_route     #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
#          predicates:                         #断言，路径相匹配的进行路由
#            - Path=/payment/test

#Eureka config
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 #每隔30秒向eureka发送信息告诉服务还活着
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:7001/eureka