server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
       git:
         uri: https://github.com/Joselyn877/springcloud-config.git
         search-paths:
           - springcloud-config
      label: main       #分支

#Eureka config
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 #每隔30秒向eureka发送信息告诉服务还活着
    instance-id: config-center3344
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:7001/eureka